# default 설정
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true

# local 설정
---
spring:
  config:
    activate:
      on-profile: "db-local"

  jpa:
    hibernate:
      ddl-auto: create-drop

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/lango
    username: guest1
    password: kakao

# dev 설정
---
spring:
  config:
    activate:
      on-profile: "db-dev"

  jpa:
    hibernate:
      ddl-auto: update

    datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://localhost:3306/lango
      username: guest1
      password: kakao